name: "tpch"
version: "1.0.0"
config-version: 2

profile: "tpch"

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  tpch:
    staging:
      +materialized: view
      +schema: staging
      +tags: ["staging"]

    intermediate:
      +materialized: view
      +schema: intermediate

    marts:
      core:
        +materialized: table
        +schema: core
      reporting:
        +materialized: table
        +schema: reporting

tests:
  +store_failures: true
  +severity: error # or warn

  tpch:
    +tags: ["tpch"]
    marts:
      +tags: ["core"]
      +severity: error
    staging:
      +severity: warn

seeds:
  tpch-project:
    +enabled: true
    +schema: reference
    +quote_columns: false
    reference:
      ref_calendar:
        +column_types:
          date_id: varchar(8)
          date: date
          year: integer
          quarter: integer
          month: integer
          week: integer
          day_of_week: integer
          is_weekend: boolean
          is_holiday: boolean
          fiscal_year: integer
          fiscal_quarter: integer
      ref_regions:
        +column_types:
          region_id: integer
          region_code: varchar(2)
          is_active: boolean
          valid_from: date
          valid_to: date
    static:
      shipping_modes:
        +column_types:
          mode_id: integer
          mode_code: varchar(4)
          estimated_days: integer
          cost_multiplier: decimal(10,2)
          is_active: boolean
          valid_from: date
          valid_to: date
