name: 'tpch'
version: '1.0.0'
config-version: 2

profile: 'tpch'

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
analysis-paths: ["analyses"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
    - "target"
    - "dbt_packages"
    - "logs"

models:
  tpch:
    staging:
      +materialized: view
      +schema: staging
      +tags: ['staging']
      
    intermediate:
      +materialized: view
      +schema: intermediate
      
    marts:
      core:
        +materialized: table
        +schema: core
      reporting:
        +materialized: table
        +schema: reporting

tests:
  +store_failures: true
  +severity: error  # or warn
  
  tpch:
    +tags: ["tpch"]
    marts:
      +tags: ["core"]
      +severity: error
    staging:
      +severity: warn