name: DBT CD

on:
  push:
    branches: [ main ]

jobs:
  dbt-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-postgres
        dbt deps
    
    - name: Run dbt
      run: |
        dbt run --target prod
    
    - name: Generate docs
      run: |
        dbt docs generate
    
    - name: Deploy docs
      run: |
        # Add your documentation deployment steps here
        echo "Deploying documentation..." 