name: DBT CI

on:
  pull_request:
    branches: [ main, develop ]
  push:
    branches: [ main, develop ]

jobs:
  dbt-test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install dbt-core dbt-postgres
        dbt deps
    
    - name: Run dbt tests
      run: |
        dbt test
    
    - name: Lint SQL
      run: |
        pip install sqlfluff
        sqlfluff lint models/ 